version: '3'

tasks:
  default:
    desc: list tasks
    cmd: task --list-all

  test:
    desc: run golang testing
    cmd: go test -v -count=1 ./...

  cache:
    desc: cache dependencies
    cmd: go mod tidy

  stop:
    desc: terminate application
    cmd: docker-compose down --volumes

  start:
    desc: run application
    deps: [stop,cache]
    cmd: docker-compose up -d --build --force-recreate

  logs:
    desc: list logs
    cmd: docker-compose logs -f